MOUSEKEY_ENABLE = no    # Mouse keys
RGBLIGHT_ENABLE = no    # Enable WS2812 RGB underlight.
VIA_ENABLE      = yes
VIAL_ENABLE     = yes
OLED_ENABLE     = no
OLED_DRIVER     = SSD1306
EXTRAKEY_ENABLE = yes
LTO_ENABLE      = yes
QMK_SETTINGS    = yes
COMBO_ENABLE    = yes
VIAL_INSECURE   = yes
